index:
  path: /dashboard/languages
  controller: Selene\Modules\LanguageModule\Http\Controllers\LanguageController@index
  methods:
    - GET
  permission: LanguageModule

create:
  path: /dashboard/languages/create
  controller: Selene\Modules\LanguageModule\Http\Controllers\LanguageController@create
  methods:
    - GET
  permission: LanguageModule.add

store:
  path: /dashboard/languages
  controller: Selene\Modules\LanguageModule\Http\Controllers\LanguageController@store
  methods:
    - POST
  permission: LanguageModule.add

edit:
  path: /dashboard/languages/{{language}}/edit
  controller: Selene\Modules\LanguageModule\Http\Controllers\LanguageController@edit
  methods:
    - GET
  permission: LanguageModule.edit

update:
  path: /dashboard/languages/{{language}}
  controller: Selene\Modules\LanguageModule\Http\Controllers\LanguageController@update
  methods:
    - PUT
    - PATCH
  permission: LanguageModule.edit